2020-09-30 20:35:34.925 | INFO     | __main__:serve:85 - 启动服务: 192.168.1.102:58636
2020-09-30 20:35:34.926 | INFO     | __main__:serve:88 - 服务注册开始
2020-09-30 20:35:34.932 | INFO     | __main__:serve:95 - 服务注册成功
2020-09-30 20:39:20.443 | ERROR    | grpc._server:_call_behavior:435 - An error has been caught in function '_call_behavior', process 'MainProcess' (36096), thread 'ThreadPoolExecutor-0_0' (41356):
Traceback (most recent call last):

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\Lib\threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x000001429A5E2DC0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 41356)>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\Lib\threading.py", line 932, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x000001429A5E2AF0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 41356)>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\Lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 41356)>
    │    │        │    └ (<weakref at 0x000001429C669310; to 'ThreadPoolExecutor' at 0x000001429C4F7310>, <_queue.SimpleQueue object at 0x000001429C4F...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 41356)>
    │    └ <function _worker at 0x000001429C4FE0D0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 41356)>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\Lib\concurrent\futures\thread.py", line 80, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x000001429C4FE1F0>
    └ <concurrent.futures.thread._WorkItem object at 0x000001429C716F70>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\Lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x000001429C716F70>
             │    │   │    └ [<grpc._cython.cygrpc.RequestCallEvent object at 0x000001429C70FA40>, <grpc._server._RPCState object at 0x000001429C716940>, ...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x000001429C716F70>
             │    └ <function _unary_response_in_pool at 0x000001429C52BAF0>
             └ <concurrent.futures.thread._WorkItem object at 0x000001429C716F70>

  File "C:\Users\Administrator\Envs\mxshop_srv\lib\site-packages\grpc\_server.py", line 552, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <bound method GoodsServicer.BatchGetGoods of <goods_srv.handler.goods.GoodsServicer object at 0x000001429C504880>>
                        │              │          └ <grpc._server._RPCState object at 0x000001429C716940>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x000001429C70FA40>
                        └ <function _call_behavior at 0x000001429C52B700>

> File "C:\Users\Administrator\Envs\mxshop_srv\lib\site-packages\grpc\_server.py", line 435, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x000001429C877E80>
                           │        └ id: 421
                           │          id: 422
                           │          
                           └ <bound method GoodsServicer.BatchGetGoods of <goods_srv.handler.goods.GoodsServicer object at 0x000001429C504880>>

  File "C:\Users\Administrator\PycharmProjects\mxshop_srvs\goods_srv\handler\goods.py", line 100, in BatchGetGoods
    goods = Goods.where(Goods.id.in_(request.id))
            │           │     │      │       └ <google.protobuf.internal.python_message._FieldProperty object at 0x000001429B4FEF40>
            │           │     │      └ id: 421
            │           │     │        id: 422
            │           │     │        
            │           │     └ <peewee.FieldAccessor object at 0x000001429B7800D0>
            │           └ <Model: Goods>
            └ <Model: Goods>

AttributeError: type object 'Goods' has no attribute 'where'
2020-09-30 20:39:46.954 | INFO     | __main__:on_exit:26 - 注销 6fc6057c-0319-11eb-8216-40b0760ebfa7 服务
2020-09-30 20:39:46.959 | INFO     | __main__:on_exit:28 - 注销成功
